repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: mkdocs.yml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.6.3
  hooks:
  - id: uv-lock
